### ISSUE TITLE
Update notice is broken in edit attachment page 

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#248]
![update-notice-broken](https://cloud.githubusercontent.com/assets/3038156/9446860/52ec8002-4a94-11e5-9d64-9529c23ae1be.png)

**Comment by eri-trabiccolo** [comment]
Ah funny.
This is because we pass the update notice text to the_content filter (callback prepend_attachment is the responsible). I bet you wanted to use the convert_smilies (at least) and some other "beautifiers". 
I think we should use a different filter hook and hook some of those callbacks so we can better handle what is really needed. For example we use 'the_content' filter also to parse imgs .. when the img smartload is active you'll see "blank" images.
PR coming soon.

**Comment by Nikeo** [comment]
yes good point !!
