### ISSUE TITLE
Breadcrumb + Woocommerce: double Shop page link

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#308]
https://wordpress.org/support/topic/double-homepage-link-breadcrumbs-woocommerce?replies=7#post-7456217

Looks like that when you chose non default permalink structure under Product permalink base, for example "Shop Base" you have two entries in the breadcrumb in woocommerce contexts pointing at the same page (the shop page) but named:. 
1) The name of the page you selected as shop page
2) The generic "Products"

What can we do as general rule, maybe, is never show the "Products" taxonomy but the Page name selected as shop page.
Dunno if there's a simple way to do that, the breadcrumb code is something I never looked at for more than 30 sec  (feaaaaaaaar) :D

**Comment by giorgioriccardi** [comment]
Hey Rocco,
I looked at the breadcrumb code for quite a bit... and I still can't find my way ;-)
The issue might be related to CPT and CT together.
This question was somehow related to the same issue?!
https://github.com/presscustomizr/customizr/issues/294

**Comment by eri-trabiccolo** [comment]
Not sure they're related, 'cause for woocommerce the breadcrumb actually prints the Products (is that a custom taxonomy, righ? :D), I really don't know so much about the breadcrumb code to tell you they are :D. For sure there's something to improve in the breadcrumb, which is a huge and convoluted piece of code, it might require some time to debug it (once understood :P). 
Anyway the breadcrumb must be a very tricky feature otherwise wordpress would have integrated it :/

**Comment by giorgioriccardi** [comment]
It is tricky for sure. Customizr is doing awesome on this.
I just completed a test using woocommerce and I got the same outcome:
when you select the custom-taxonomy or in my case "product-category" the breadcrumb doesn't return the ./product-category/veggies but only the custom category itself ./veggies.
Maybe Nicholas wanted to be that way because it's cleaner, but definitely it is a complicated part.

It relies on an older version of breadcrumb-trail (0.5.3) https://github.com/presscustomizr/customizr/blob/master/inc/parts/class-content-breadcrumb.php#L121 that now it is quite outdated: https://en-ca.wordpress.org/plugins/breadcrumb-trail/developers/

Did not debug yet, I'll keep trying.

**Comment by eri-trabiccolo** [comment]
Well yes, but Nicholas highly changed it, I think..
Anyway yes your latest test is related, but it's not the topic of this Issue.
This issue regarded to the fact that there were a double shop trail in the breadcrumb under some permalinks structure condition, that's why I couldn't say it was related, I just don't know it :D 
Thanks for your tests, let us know what do you discover!!! :D

**Comment by giorgioriccardi** [comment]
Hey Rocco,
I tested extensively the issue of that german guy you linked at the top. 
I can not reproduce the issue and I highly stressed permalinks structure and also shop settings.

The breadcrumb is always behaving like it is suppose to...

and while I was there I also found the solution for the other issue I had with CPT and CT ;-)
https://github.com/presscustomizr/customizr/issues/294

**Comment by eri-trabiccolo** [comment]
Glad you find the solution for the CPT and CT issue.
About the issue in this topic, I would like to say "GREAT" but the thing is that, I'm able to reproduce his issue when I change the Product permalink base in something different than the default.
http://prntscr.com/8jv1rv
http://prntscr.com/8jv1zc
mah, there must be something in my and his permalinks...

**Comment by giorgioriccardi** [comment]
Still I can't reproduce it, but FYI no matter what I do with permalinks I always get the custom base set by WP:
http://awesomescreenshot.com/0d759mykac

**Comment by eri-trabiccolo** [comment]
Ah yeah me too, when I set "Shop base" the "Custom base" radio is selected and its field filled, I think it's normal.

What do you get in the breadcrumb?
Shop? or Products?
I get both
http://prntscr.com/8jv1rv

**Comment by giorgioriccardi** [comment]
All regular for me:
http://awesomescreenshot.com/08459n0fa5
http://awesomescreenshot.com/03e59n0h5f

**Comment by eri-trabiccolo** [comment]
Which is fine if your shop page is called Products, otherwise it should display the shop page name (according to the permalinks).
Weird that it displays both here (and to that user too)

**Comment by giorgioriccardi** [comment]
I don't know if this helps but I did a test with 2015 theme and Breadcrumb Trail plugin activated.
Instead of Products I get the proper category:
http://awesomescreenshot.com/0f659n44c7
and more in specific for the product itself: http://awesomescreenshot.com/02b59n495e

So where is the trick? When Customizr displays "Products" is it doing something custom?
I'll try with another theme that supports breadcrumbs so I don't have to use the plugin.

**Comment by eri-trabiccolo** [comment]
It's displaying the taxonomy "Products" I think.

**Comment by giorgioriccardi** [comment]
Tested with other themes I always get the taxonomy name but I can't reproduce the issue.
Tested on 2 different sites!
No idea what might be the difference/issue?!

**Comment by eri-trabiccolo** [comment]
Mah :D 
Thanks for all your tests! ;)
