### ISSUE TITLE
Once deleted, and re-created, the front page slider does not reappear

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#318]
This is with reference to the [WP forums post ](https://wordpress.org/support/topic/missing-front-page-slider?replies=4#post-7464808). I replicated the same problem.

CustomizrPro version 1.2.6
Create a slider. Choose it on front-page.
Now, delete the slider.
Now, recreate a slider of same or different name.
Choose this new slider for front-page.
The slider does not appear.

**Comment by eri-trabiccolo** [comment]
Thanks for reporting this menakas :) 
Though I'm actually not able to reproduce this. :/
Are we talking about setting it from the slider settings in the front page section (of the Customizer), right?
'Cause I see in that wp forum post that user talks about setting it in the static page, not sure whether he means "also" or "only". The slider's on the front page must be set in the Customizer, the one set in the Page selected as front page will not be picked up.
Weir anyway, the only thing I can think about (if it's not the case above - slider set in the page) is something wrong in our stored options. :(

**Comment by menakas** [comment]
Hi eri-trabiccolo,
I saw your resolution of the issue on the WP forums. I too did not name it *home-page-slider*. It seems to be a newbie issue. Is there some way of ensuring that the user name it *home-page-slider* only?

**Comment by eri-trabiccolo** [comment]
Well mine was more a work-around than a real fix. :)
The home page slider hasn't a fixed name. An user can chose whatever slider. The problem is, in his(her) case, that he(she) chose a slider named "home-page-slider" once and this name was saved in the db. Then he(she) changed the slider-name but the old name was still picked up as front page slider. Reasons why this can happen:
1) cache, looks like was not that user's case
2) a problem in the theme options saved in the db
2a) It might be a bug, probably related to this -> https://github.com/presscustomizr/customizr/issues/241#issue-102558091
meaning that we have more instances of the actual options saved in the db and we look for an old one.
2b) that user  has a "corrupted" theme option.
but you were able to reproduce that too so 2b is something reproducible.

I know the name of the slider the theme picks up in a page because we pass this name to the scripts. You can see it in the html among the TCParams passed to tc-scripts
"SliderName":"something"

If I understand, you're suggesting to force the home page slider name to a specific name, right?
This for sure will avoid this issue, but we have to think to old users too, so it's something we could do just for new users. 
Overall I think this is a symptom of a general issue we have to fix.

p.s.
hopefully I was understandable :/ let me know if not ;)

**Comment by Nikeo** [comment]
not reproductible
resolved on the forum

**Comment by eri-trabiccolo** [comment]
This can be related to the mess with the options which this should fix -> https://github.com/presscustomizr/customizr/pull/473
