### ISSUE TITLE
Unable to upload Logo/Favicon

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#349]
https://wordpress.org/support/topic/again-logo-and-favicon

Seems to be a recurring problem with no root cause understood yet?

**Comment by eri-trabiccolo** [comment]
Not sure what can be the reason.
Also there's no error report form that user. For example, what happens?
Does the save button turn in "Save & publish"?
If yes when clicked does it turn to "Save"?
Also with wp > 4.3 the favicon can be loaded with the wordpress control, and handled by wordpress itself...

**Comment by rdellwebworks** [comment]
https://wordpress.org/support/topic/my-header-logo-is-gone-from-my-website-customizr

Similar one, still open.

Understand you need more details Roc, just wanted to record as it seems to have raised a few times since this latest version was released.

**Comment by eri-trabiccolo** [comment]
Yeah I remember about it. As you can see, in this case the user said it could upload the logo (the chooser dialog shown up and the user could actually upload a file 'cause the user could see that in Media), but after that something broke.
The problem is that I'm unable to reproduce them. The logo uses a Customizr specific control but the favicon, with wp > 4.3, uses a wp control. Dunno what's happening there.
With latest wp or Customizr?

**Comment by ghost** [comment]
Customizr now uses built-in logo upload
