### ISSUE TITLE
Gist issue

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#350]
https://wordpress.org/support/topic/search-form-above-the-main-menu

Error with one of Rocco's gists

**Comment by eri-trabiccolo** [comment]
Ok this is not a theme's issue, nor a specific error in the gist (it was for a woocommerce serach form). Anyways gists I wrote for users have to be intended as per specific request and most important per theme's version.
I cannot maintain all the small gists I wrote (and in this case there's nothing to maintain :D) that's the main reason why they never become official snippets on presscustomizr.com. :)
Thanks for reporting this Dave, but since isn't a theme's issue I'll close this issue ;)

Bests.

Rocco
