### ISSUE TITLE
v3.4.11 Conflict withThe Events Calendar?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#353]
Posted on the forum : https://wordpress.org/support/topic/new-version-the-events-calandar-conflict?replies=2#post-7541254

Hello,

My events calendar plugin is not working. It has worked fine for the past 6-8 months using your theme until I upgraded the theme the other day. Now all i get is an archive page. Here is the thread of support from the events calendar and we were able to diagnose a conflict with the theme. Please help.

https://theeventscalendar.com/support/forums/topic/events-calendar-only-showing-archive/

http://www.jaxterror.com/events

**Comment by eri-trabiccolo** [comment]
Just done this.
Remains a small problem.
When the View (a calendar) is shown as Month (you can show it as Month, List, Day) our breadcrumb doesn't get the tax "Events".
Want to see if I can force this.
Let you know in a while.

**Comment by Nikeo** [comment]
Cool Rocco. Thanks :)

**Comment by eri-trabiccolo** [comment]
Ah, it's because they filter the post_type_archive_title in the "Month" template, that we use in the breadcrumb.
This is actually something which doesn't seem to have any impact on our theme, but I don't want really mess with their code, maybe they have some reason I'm not aware of, so I'll copy the wp function to retrieve the archive title we display in the breadcrumb trail.

**Comment by eri-trabiccolo** [comment]
two alternatives...
