### ISSUE TITLE
Thumbnails in Featured Pages gets partially hidden when location is set to before header.

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#390]
Hi,

In Appearance -> Customize -> Content -> Featured Pages -> Select a location
Set it to -> Before header.

In Appearance -> Customize -> Header -> Navigation Menus -> Main menu design -> Select a design : side menu (vertical) or regular (horizontal)
I have selected -> Regular (horizontal)

In Appearance -> Customize -> Header -> Design and Layout -> STICKY HEADER SETTINGS
I have -> Sticky on scroll -> checked.

View on front end, the thumbnails gets partially hidden underneath the header.
Please see screenshot. http://i.imgur.com/kzdfLQ8.png

Same thing happens with or without thumbnails.

Happens in Customize Pro 1.2.12
Do not know if this bug exist in previous versions.

Thanks!
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks for reporting this Denzel.
Yes this issue is here from the beginning :)
I think we have just 2 decent ways to fix it:
1) prevent sticky header where fpu are shown and if hooked before the header (weak)
or
2) filter the stickyCustomOffset but also localize the trigger height 
what do you think @nikeo?

**Comment by Nikeo** [comment]
@denzelchia  thanks !
@eri-trabiccolo I don't know yet , but I think this sticky header has to evolve in the future version !

**Comment by eri-trabiccolo** [comment]
Sure ( yes I remember the scroll-aware thoughts)
