### ISSUE TITLE
WPML compatibility prevents switch of language when http redirect based on browser's language is chosen

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#408]
https://wordpress.org/support/topic/wpml-compatibility-prevent-switch-of-language

I'm unable to reproduce this issue though.
Still trying.
Anyone able to reproduce it?

**Comment by eri-trabiccolo** [comment]
Looks like it was due to a caching issue (w3tc).
On another subject, looks like the user have an old wpml version (probably, as I don't see the option he's referring to, mine is different). This poses a question:
What's our compatibility policy with plugins? As for now, basically, we make our compat codes work with the latest plugin versions. This is quite fine with free plugins as generally users keep them updated, but what about premium plugins? It's not unusual that users might have outdated premium plugins, 'cause for example they decide to not renew the license.
Also, we support very old wp versions, this "implies" also old plugins versions. Till now we've been "lucky" (also 'cause we check the existence of an external function before using it, most of the times) but in the future we might have some issues.

**Comment by Nikeo** [comment]
Hi Rocco, thanks for raising this problem.

I think the user has the reponsibility to have the latest version of WordPress and plugins installed.

For WordPress, we've made an exception since it might be complicated sometimes to upgrade the CMS when many customizations have been done.
However, for the plugins let's focus on the latest version only and communicate clearly about this to the users.

**Comment by eri-trabiccolo** [comment]
Hi Nico,
perfect. I close this then. ;)
