### ISSUE TITLE
Turkish language file named wrongly

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#427]
Hi,

With reference to this thread on WordPress.org forum.
https://wordpress.org/support/topic/turkish-language-7?replies=7#post-7716296

The language file tr.mo and tr.po should be named as tr_TR.mo and tr_TR.po

Thanks!

**Comment by Nikeo** [comment]
thanks for reporting Denzel :)

**Comment by eri-trabiccolo** [comment]
Thanks for this Denzel.
This is a tricky topic, how wordpress handles translations?
I read somewhere someone complained about the fact that wordpress doesn't fall back on a "similar" lang in those kind of situation. For example, if an user has just `tr` as lang code those translations will be picked up, if he has `tr_TR` they will be not, but also if we rename them to `tr_TR` we'll have the same problem (reversed).
I tend to agree with those complains, Wordpress should take care about a sort of fall back.
Also, sure Nicolas hasn't translated the theme in Turkish, hence someone did it, hence this guy, supposedly tested it, this means that he/she has `tr` and not `tr_TR` as lang code.
Looking here though -> https://make.wordpress.org/polyglots/teams/
the correct lang code for Turkish is actually `tr_TR` but what if there are users having just `tr` as lang code? We'll have complains from these like "After latest update my website isn't localized anymore" :)
So, IMHO, we should keep the `tr` files and add also `tr_TR` (just a copy of `tr`).
What do you think guys?

**Comment by Nikeo** [comment]
OK.
Except the fact that it will add some kbytes to the theme, I think it's the wiser solution and have nothing against it.

**Comment by eri-trabiccolo** [comment]
Mmm something like 100K ?, could this be a problem?

**Comment by Nikeo** [comment]
no

**Comment by eri-trabiccolo** [comment]
:D

**Comment by eri-trabiccolo** [comment]
My poedit tells me that there's also a tr_CY ( Turkish - Cyprus ) that's the problem when you can't fall back !!!

**Comment by denzelchia** [comment]
Hi Rocco,

Login to WordPress admin -> Settings -> General -> Site Language
Use developer tools to look at the option values of that drop-down list.
Only those on this list is supported by WordPress, tr_CY is not supported.

When user select the Site Language at this option, WordPress will find the relevant language file within the Theme and load it. If WordPress cannot find the language file with name similar to the selected option value, it will not load any Theme translation.

Hope this helps. :)

Thanks!
Denzel

**Comment by eri-trabiccolo** [comment]
:)
I actually don't have anything in the select options except for the English (United States). Do I probably need a lang pack?
Anyway if I put `define('WPLANG', 'tr')` (tough it's deprecated) in my wp-config.php the tr.mo is picked up.
Anyway what you say perfectly fits the list in the link above (https://make.wordpress.org/polyglots/teams/) `tr_TR` is the wp supported lang code for basic turkish lang. 
My sentence about the `tr_CY` was just about the fact that it exists, and might be supported in the future, and about the fact that WP atm has no fall-back system. For example, we have France's french lang files, but we don't have Belgium's french files, and that should be supported ( always according to the list at that link)*
If you then chose the fr_BE (Français de Belgique) - equivalently set the WPLANG constant to that - you'll see that our fr_FR isn't picked up. I don't know whether or not this is a good choice (by wp) as I don't know the differences between the two languages (I presume they shouldn't be that much, but anyways), but that's the lack of fall-back I was talking about :D
So I'm aware of:
> If WordPress cannot find the language file with name similar to the selected option value, it will not load any Theme translation.
But the problem is that it's not about "similar name" but "exactly the same language code" :D 

At the end of this speech, anyway, I think you're right, we should stick on the wp supported language codes so we should get rid of the `tr` po/mo files.
I'll open a different PR that depends on 428.
Thanks for this exchange of views Denzel! ;)

*
the actual list of available translations can be retrieved with:
https://developer.wordpress.org/reference/functions/wp_get_available_translations
