### ISSUE TITLE
Customizr theme and Advanced AJAX Page Loader plugin.

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#447]
Following a user request, I was wondering if adding the compatibility with this plugin would be interesting.

There's a Theme's guide here for this plugin https://wordpress.org/plugins/advanced-ajax-page-loader/faq/ 

Did not try anything yet.

**Comment by eri-trabiccolo** [comment]
Not sure,
have to see. We have jquery things which are fired on document ready (see smartload and centering). We might need to add some event listener (I'm just thinking loud, I don't exactly know what that plugin does, just wondering reading its descriptive name :D).
Also I thought that sooner or later this could have been a theme's feature, also looking at the development of the REST API ( framework in the core since 4.4 ).

p.s.
the theme's guide there isn't very exhaustive :P eheh

**Comment by eri-trabiccolo** [comment]
Just took a look at it (meaning that I ran it).
Basically it will never work with Customizr :D 
It reloads what's in the "#content" but its based on the idea of that a theme follows the standard wordpress templates system (I think), which ... well.. we don't follow at all.
Also, for example, say we're in home where there is the slider before the #content we'll see it when loading another page.
We can even use "#tc-page-wrap" as content element ID but .. what would be the point if we have to re-load everything (btw this still doesn't perfectly work).
We do too many things when worpdress requests a new page. (consider that the body class doesn't change when passing from an article to a post list with this plugin, even if there's some settings we can fill which might solve this). I think this plugin could be fine with very simple themes but arguably not (never) with Customizr :)
If we really want to provide this feature we should do it by ourselves (maybe looking at this plugin's code as inspiration).

**Comment by eri-trabiccolo** [comment]
Also should be noted that such an approach is diametrically opposed to the contx(++), which aims to build single contexts as if they were stand alone websites, always IMHO :)
