### ISSUE TITLE
Logo : select the logo from media library

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#455]
replace the current logo uploader by a smarter one (WP buiit-in should work fine), enabling user to select from media library or upload a new file.
=> might need some customizer js coding
=> there might be some retro-compat issue with the way we currently store the attachment id in the db

**Comment by eri-trabiccolo** [comment]
Not sure about the bullets.
I think we can use the new media controls for wp>=4.2 (https://make.wordpress.org/core/2015/07/16/new-customizer-media-controls-in-4-3-and-4-2/) and use the current system otherwise.
Haven't dig into that yet but for what I can read it stored the attachment id.

**Comment by eri-trabiccolo** [comment]
I just tested this:
`              'tc_logo_upload'  => array(
                                'control'   =>  'WP_Customize_Cropped_Image_Control' ,
                                'label'     =>  __( 'Logo Upload (supported formats : .jpg, .png, .gif, svg, svgz)' , 'customizr' ),
                                'title'     => __( 'LOGO' , 'customizr'),
                                'section'   => 'logo_sec' ,
                                'sanitize_callback' => array( $this , 'tc_sanitize_number' )
              ),`

it's pretty fine.
The problem is that svg are not allowed (if we use the cropped constructor it raises an error when cropping it, otherwise ), and of course cropping an animating gif means crop a static frame of it.
On the other side, the basic `WP_Customize_Image_Control` returns an url and not the attachment ID, which isn't a big issue (we just have to change the remove the sanitize number callback) =>
`              'tc_logo_upload'  => array(
                                'control'   =>  'WP_Customize_Image_Control' ,
                                'label'     =>  __( 'Logo Upload (supported formats : .jpg, .png, .gif, svg, svgz)' , 'customizr' ),
                                'title'     => __( 'LOGO' , 'customizr'),
                                'section'   => 'logo_sec' ,
 //                               'sanitize_callback' => array( $this , 'tc_sanitize_logo_attachment' )
                            ),`

So, what we have to decide, IMHO is:
a) do we want to look for a way to allow cropping of svgs? (will wp be able to do that? don't think so)
b) do we want to extend WP_Customize_Image_Control creating a custom control which will return an ID (in js)?

We can use this control also for the default thumbs (and in the future for FPU), always if we want to allow svgs (animated gif will be "downgraded" to a frame anyways when a thumbnails - image_size - is created, which is not unlikely for our thumbs ), otherwise use the Cropped version.

Also consider that the `WP_Customize_Image_Control` is available since wp 3.4.0

Let me know your thoughts ;)
