### ISSUE TITLE
FW0015 (Feature) Show random posts in the front page

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#491]
https://wordpress.org/support/topic/how-to-show-random-posts-in-the-front-page

Menaka provided a solution. Could it be new option in core?

**Comment by Nikeo** [comment]
yes could clearly be included in the core.
Just a conditional checkbox when post list is selected on home (would only affect home).

**Comment by Nikeo** [comment]
some tweaks might be required for the featured posts.
@eri-trabiccolo any thoughts / comments ?

**Comment by eri-trabiccolo** [comment]
Mmm not sure honeslty.
I think this sould be a snippet and nothing more.
The random order should not affect the featured posts, if I remember the way wp retrieves the posts and then performs the stickies-split .. what I'm thinking is .. what happens when you go from page1 to page2 ? (and vice-versa, meaning say we access directly to the second page and then we back to the first.. ).
I think that nothing will take care about the random ordered posts shown in the "previous" displayed page. So you might have many post occurrences in different subsequent pages.

Hence this option could be fine if the user doesn't use to show a pagination in home/blog .

If we want to add this option we have to disable the pagination (noticing the user), or just add a notice for that.

Overall my idea is, it can be good for a snippet, but not worthwhile as an actual theme option :) , available to implement it anyways ;)

**Comment by Nikeo** [comment]
oh yes the pagination will be useless.

Let's just inform users about it in a simple notice.
> Your posts will be randomly displayed on home. If your home posts are paginated (link to pagination doc : https://codex.wordpress.org/Pagination ), you might see several occurences of a given post in different pages.

**Comment by eri-trabiccolo** [comment]
Ok,
I'll check if there will be any issue with the sticky posts and will implement it.
This option will be inside the Front page section, below or above the cat picker

**Comment by eri-trabiccolo** [comment]
I forgot to say that you can even see the post more than once in different pages for the same reason (added to the notice).
And about the stickies .. of course, if you have stickies the number of the posts shown in the first page might vary depending on how many sticky posts wp finds in the "random ordered" query.
Dunno whether or not you want to add the latest thing to the notice.
(I'm about to finish and push the PR)
