### ISSUE TITLE
How to handle the mobile Jetpack module ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#497]
- adding a notice ?
- adding a plugin specific option in the same spirit of the WooCommerce section in the customizer ?

Support thread : https://wordpress.org/support/topic/mobile-not-displaying-properly?replies=7#post-7853174

**Comment by eri-trabiccolo** [comment]
Dunno why you want to consider it a comp issue :P 
What should be is that jetpack should not enable it by default. And I think it doesn't (not sure though). And if it does it's a jetpack issue, if it doesn't it's a user issue who doesn't know what he does.
I thought about the woocommerce thing too (I think notices are often skipped by users) if you want I can try to do it meaning:
Jetpack section, with something like "Allow jetpack mobile theme to replace this theme in mobile devices (requires jetpack mobile theme module enabled)" disabled by default for all new users (because maybe old users knowing what they do wanted it)

**Comment by eri-trabiccolo** [comment]
I gave to the jetpack code a rapid eyed/test.
The thing is that the "redirection" to the jp mobile theme happens before the main theme is loaded.
So I think we have two left possibilities:
1) An admin notice
or/and
2) FAQ

**Comment by Nikeo** [comment]
Ok thanks for the analysis.
I think both should be good. we need to work on a better admin notification class for Customizr before implementing it. Not a priority but let's keep this issue open

**Comment by eri-trabiccolo** [comment]
:D 
Will not be a boring year :P

**Comment by Nikeo** [comment]
not at all ! :)
