### ISSUE TITLE
JQuery conflict with Plugin Colio?

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#501]
https://wordpress.org/support/topic/jquery-conflict-47

**Comment by eri-trabiccolo** [comment]
Colio looks like a paid plugin.
Why it's always this theme which conflicts with plugins and never plugins which conflicts with this theme?
Anyway google says it depends on fancybox:
jquery.fancybox-1.3.4.min.js?ver=3.4.16:1 Uncaught TypeError: a.fancybox.init is not a function

As we know that fancybox can cause this kind of issues, long ago we enucleated it so that it could be loaded/unloaded separately.

Users can avoid loading theme's fancybox by disabling these options:
Appearance -> Customize -> Content .. -> Galleries -> Enable Lightbox effect in galleries
Appearance -> Customize -> Global settings -> Image settings -> Lightbox effect on images

Of course this means that they also lose those effects, which maybe they're not even interested too.

**Comment by rdellwebworks** [comment]
Rocco provided workaround so Closing
