### ISSUE TITLE
Jetpack xmlrpc.php issue raised in a couple of posts (same User)

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#504]
https://wordpress.org/support/topic/feed-dead-and-also-my-jetpack-subscription-plugin-not-working

**Comment by eri-trabiccolo** [comment]
Anyone able to reproduce this?
Looks like I'm not..

Let's keep this open ..

**Comment by giorgioriccardi** [comment]
One of my clients had a similar issue that was caused by the i-Themes-Security plugin.
It has a setting at the very bottom of a long list that is confusing if you don't read it carefully:
http://awesomescreenshot.com/0ea5kqqk6a
Maybe that user has a similar plugin or even the same one,
hope it helps

**Comment by Nikeo** [comment]
Unable to replicate. Might be a plugin collision.

Customizr doesn't modify the xmlrpc.php file.
