### ISSUE TITLE
Number of menu item limitation in WordPress ?

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#506]
I've never heard about such a limit in WP ?
As reported by a user : 
> Hi,

> I am currently working with the Customizr theme, and want to buy the Customizr Pro, but need to have an answer on the following question first;

> Is it possible to make more than 90 menu items (including parent and child menu) with Customizr Pro? I am using the "lite" version now and I am not able to make more than 90 menu items. I have changed from normal webhotel to VPS because I thought this was the reason but apparently it was not.

**Comment by eri-trabiccolo** [comment]
Should not be a wp limit, but a php (max var) limit. It has been raised several times actually. But is theme independent, or better Customizr looks like morr "expensive" than a standard wp theme, so it happens more frequently with our theme. Anyway is something solvable increasing some php directive in php.ini, I don't remember them now, but I found them googling for something like "wp menu items limit". Will look more into it when I back so that we can make a DOC.

**Comment by Nikeo** [comment]
OK thanks !

**Comment by eri-trabiccolo** [comment]
These are the sources I was referring to:
https://wordpress.org/support/topic/menu-item-limit-1?replies=21
http://www.wpbeginner.com/wp-tutorials/how-to-fix-the-custom-menu-items-limit-in-wordpress/
http://www.mhthemes.com/support/how-to-remove-wordpress-menu-items-limit/

I don't think is something we can do much about
