### ISSUE TITLE
FW0027 Woocommerce CSS issue

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#514]
https://wordpress.org/support/topic/woocommerce-cart-checkout-table-line-color-css

**Comment by Nikeo** [comment]
As reported by the user : 
m using Customizr and WooCommerce and noticed some slight CSS anomalies on the cart and checkout pages, specifically in the tables around the "cart total" and "your order" where the borders/lines of the tables use the theme color.

Cart Specifics
The vertical theme color lines on the table are only using the theme color in the first column and do not go all the way across or on the 2nd column. Seems to be the lines above and below "shipping" row.

The vertical line under the total seems to be extra thick in column 1 rather than the same thickness/height all the way across.

Checkout Specifics
Same issue as the cart with the theme color lines only being color in the first column above and below the shipping row.

Also the theme color line below the total on checkout is also only theme color in the first row not all the way across/the 2nd row.

This shows up on the demo site, http://demo.presscustomizr.com/cart/ and http://demo.presscustomizr.com/checkout/ (you have to add something to the cart first) so it appears to be something with the base theme rather than any customizations I have done. Although I know a few CSS basics to adjust things and inspecting elements via browser tools, I haven't been able to isolate this one so I can correct it with some extra CSS in my child theme.

If anyone can assist with posting something to clean this up that would be great and then hopefully it could be built into the core theme as well at some point.

Thanks in advance, Simon

**Comment by eri-trabiccolo** [comment]
The solution would be what I replied to the user.
Look that we have some other CSS "issues" with woocommerce and other similar plugins.
Basically it's about the input height.
Bootstrap2 (I think, or anyways our custom css) sets a fixed height for several text-like(email, normal text, numbers) inputs. The thing is that woocommerce and other plugin use to apply the `box-sizing: border-box;` rule to some inputs + some padding. 
This results in inputs very tight (mostly in height) making the filled inputs pretty much unreadable.
Do we want to remove the fixed height overall for the inputs text-like?

**Comment by Nikeo** [comment]
I think we shoud override this yes. Write some additional css rules in the compatibility php class.

**Comment by eri-trabiccolo** [comment]
Which bit? The input height?
The thing is that isn't only about woocommerce, but several other plugins.
If we don't want to care about other plugins ok.

**Comment by Nikeo** [comment]
only the plugins already listed in the compatibility class

**Comment by eri-trabiccolo** [comment]
Mmm, ok.

**Comment by eri-trabiccolo** [comment]
Here's where b2 sets the inputs height and font-size:
https://github.com/presscustomizr/customizr/blob/master/inc/assets/less/bootstrap/forms.less#L66
https://github.com/presscustomizr/customizr/blob/master/inc/assets/less/bootstrap/forms.less#L45

I still think these should not be set (so they're inherited), but oh well we'll go with the woocommerce (and other plugins) CSS override then we'll see with the new CSS framework
