### ISSUE TITLE
Arabic characters issues

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#547]
the arabic letters on the header are seperated

**Comment by eri-trabiccolo** [comment]
I think this is an old issue we discussed.
Do you mean in the menu items?

**Comment by eri-trabiccolo** [comment]
maybe found it in the old todolist:
also there's a problem with the first letter for menu-item with arabic lang => https://wordpress.org/support/topic/persian-menu?replies=8#post-6474318

**Comment by eri-trabiccolo** [comment]
So..
What do you think about removing the first-letter thing in Customizr  (and its reverting in WFC)?
I tested the first-letter styling cause that issue.
IMHO, when moving to the new CSS framework, we'll get rid of it anyways.
Otherwise we can, at least, make the WFC "first-letter" fix depending on the same Customizr condition:
https://github.com/eri-trabiccolo/customizr/blob/master/inc/parts/class-header-menu.php#L506
