### ISSUE TITLE
Impress listings plugin compatibility issue

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#548]
Hello I am using Customizr Pro with the free Impress Listings (previously known as WP Listings) plugin. The problem I am having is the plugin seems to conflict with the theme because the layout does not display correctly. Main thing I notice is the sidebar is displayed under the content. I'm pretty sure this has to do with the 'content wrapper' similar to posts I see about WooCommerce and other plugins that don't use the same content wrapper HTML ids that Customizr Pro uses.

This plugin settings has an option to handle this (I think) but I can't seem to get it to work. The setting is "Use custom wrapper" and has two text fields, one for the beginning tags and one for the end tags. I've tried inputting the div tags to no avail.

See the details below from the plugin's settings page:

---

Custom Wrapper (enabled)
If your theme's content HTML ID's and Classes are different than the included template, you can enter the HTML of your content wrapper beginning and end:

Wrapper Start HTML: TEXT FIELD
## Wrapper End HTML: TEXT FIELD

These pages show the problem with the layout. Notice the sidebar is on the bottom of the page.

A single listing
http://www.teamwaller.com/listings/freezeland-view-ln-linden-va-22642-300010566520/

List of listings shows the same issue
http://www.teamwaller.com/listings

**Comment by eri-trabiccolo** [comment]
Well we cannot do that much.
Look e.g at their single template -> https://github.com/agentevolution/wp-listings/blob/master/includes/views/single-listing.php#L455
they have comp code for genesis and equity themes, if the conditions are not satisfied they print out the code (which prints the sidebar anyways)
Custom wrapper option isn't good for us as we have hooks (so php and not only html) in our "wrappers". We probably can play with our own hooks located in header and footer to print our wrapper but .. how can we avoid the sidebar loading? Really dunno.
If they had another "compatibility check" like
`elseif (function_exists('genesis_init')) {
...
}elseif( apply_filters('wp_listings_theme_compat', $options['wp_listings_theme_compat]) ){
  do_action('wp_listings_custom_single');//<--
}else{..
`
we could hook on that and use our own code, otherwise, 99.9% the only thing we can do, IMHO, is provide custom templates (to override theirs), but this means that we have to check if they work every time the plugin updates, and release a new version of the theme if needed...

**Comment by denzelchia** [comment]
@Nikeo @eri-trabiccolo 
Hi Guys,

Customer is asking for the status of this issue.
Are we able to provide a solution?
What's the plan or progress?

https://secure.helpscout.net/conversation/168266831/8579/?folderId=631714

Thank you,
Denzel

**Comment by eri-trabiccolo** [comment]
@denzelchia 
So as I said, I cannot see any plugin's API to achieve that.
The only way, then, remains overriding their templates in the theme (or better a child theme) directory.
Basically copying their templates for single and archives and make some changes to them.
Of course this cannot be considered an official compatibility code, this means that users who want to use the templates below should do that at their own risk :D 
https://gist.github.com/eri-trabiccolo/15bd4dcc36c2f7394fb7#file-single-listing-php

(keep the filename, e.g. `single-listing.php` in the theme|child-theme's directory)

**Comment by denzelchia** [comment]
Thank you!

**Comment by eri-trabiccolo** [comment]
:D
