### ISSUE TITLE
WP Ultimate Recipe Plugin Compatibility

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#551]
Hi,

With reference to this helpscout thread.
https://secure.helpscout.net/conversation/168751859/8697/?folderId=631714

I made a test on localhost Customizr Pro, 
Downloaded and Installed this plugin. https://wordpress.org/plugins/wp-ultimate-recipe/screenshots/
I am able to create a recipe and use the shortcode in a page.
Screenshot of shortcode. http://i.imgur.com/z1JbDeA.png
Screenshot of recipe produced by shortcode in a page. http://i.imgur.com/2OeCa9R.png

The problem is the plugin's shortcode editor is unable to work properly.
I can see the recipes options in firebug but is able to make the shortcode editor dropdown work.
Please see screenshot. http://i.imgur.com/aFkwfYi.png

This could be a Javascript conflict with our theme.
Are we able to help on this issue?

Thank you.
Denzel

**Comment by eri-trabiccolo** [comment]
Mmm so is about the dropdown?
Will check this asap ;)

**Comment by Nikeo** [comment]
you never stop to work !!! :D

**Comment by eri-trabiccolo** [comment]
Eheh, I need something to do otherwise I'll end up to study french ;)
Anyway I'm about to leave from this ip looking for a pillow :D

**Comment by eri-trabiccolo** [comment]
This happens with pro due to a select2 versions conflict.
Can you confirm this Denzel? (meaning, works fine with the free theme)

**Comment by denzelchia** [comment]
Hi Rocco,

Just tested.
Yes, works with Customizr Free theme.
http://i.imgur.com/xYGnz4n.png

Thank you,
Denzel

**Comment by eri-trabiccolo** [comment]
Perfect Denzel,
I'm on it ;)

Thanks!

**Comment by eri-trabiccolo** [comment]
Thanks Denzel will be fixed in pro (private repository).
I close this then ;)

**Comment by denzelchia** [comment]
Thank you!

**Comment by jamesdkillion** [comment]
I have been desperatly trying to get a recipe data base I can install into my WP Ultimate Recipes plugion our website is running. Can anyone help me with this, or help me post a copy on here so I can look for people willing help add some recipes?

**Comment by eri-trabiccolo** [comment]
Not sure what you mean..
do you mean you're having issues with wp ultimate recipe and the Customizr theme?

**Comment by jamesdkillion** [comment]
No I am wanting to upload to github a way for contributors to add recipes to a database that can be added to wp ultimate recipes pro                                                                                                                                                                                                                                                                                                                                         James D Killion, sent from my Blackberry 10 Classic                                                                                                                                                                                                                From: Rocco AlibertiSent: Friday, May 6, 2016 2:09 PMTo: presscustomizr/customizrReply To: presscustomizr/customizrCc: James Killion; CommentSubject: Re: [presscustomizr/customizr] WP Ultimate Recipe Plugin Compatibility (#551)Not sure what you mean..
do you mean you're having issues with wp ultimate recipe and the Customizr theme?

—You are receiving this because you commented.Reply to this email directly or view it on GitHub

**Comment by eri-trabiccolo** [comment]
Ah I see what you mean.
Well unfortunately this is not the right place where to find this kind of "help" as this space is "reserved" to collect Customzr theme issues.
Good luck ;)
