### ISSUE TITLE
FW0033: Google AMP problem

### ISSUE THREAD

**Issue by rdellwebworks** [presscustomizr/customizr#558]
https://wordpress.org/support/topic/issues-with-amp

Google has recently launched "accelerated mobile pages" project. Generating errors, reported by 2 Users.

**Comment by andrewfandrew** [comment]
It seems that the main problem is a CDN version of Merriweather google font. Google fonts can be downloaded to a web site. I have seen a conditions technique used in page headers where if the physical version is available load that otherwise load the CDN version. Not sure what Nicolas and Rocco think about this?

Downloading the font to the theme would surely speed up page loads? I can look further into this if the main theme developers are interested..

**Comment by andrewfandrew** [comment]
There are many choices of google font available in customizr theme options. Theme users should be aware that site performance is going to be significantly affected if they choose to use google fonts. One way around it would be to offer the choice of physically downloading the font(s) or link to the CDN's?

I am assuming the path to the Merriweather CDN is correct. Otherwise the font would not work in the theme which would have triggered off issues on the subject?..

**Comment by eri-trabiccolo** [comment]
Honestly I don't know if downloading the font on the same website server will speed up stuff..
Shouldn't be the purpose of a CDN speed up stuff? Isn't google font CDN faster than a common user's server?
Dunno ..

**Comment by andrewfandrew** [comment]
Let me check this out, Rocco. I read that CDN can slow page loads a few years ago so maybe the things have changed/ improved. But CDNs are used so widely so cannot be so bad. I think there is need for more information e.g. which version of customizr are they using as they may be using an outdated font and need to upgrade to latest version of customizr? 

It is a bit funny that Google should launch a tool and all it shows is that their own fonts are slowing down the pages! That seems to be the only thing it is reporting.. What do you think? You can download google fonts to your site now. Maybe it could be considered as a future cutomizr option? The main advantage i thought of CDNs is they keep your site up to date whereas if you download the thing, when it gets out of date it stays out of date and you have to download the new version..

**Comment by andrewfandrew** [comment]
Not sure what 'the boss' thinks about this issue. I have been reading through some stuff
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/?hl=en
It looks like installing web fonts locally can be a good idea but there are a lot of pros and cons and if not configured correctly they can slow down a site. 

I like to use fonts from http://www.fontsquirrel.com/. There are lots of free ones. The quality if variable and you need to test them out. They are only available for download- no CDN versions. But there are some pretty cutting edge ones.. What could be cool would be a customizr option to download a fontsquirrel font and it gets installed. Not sure how difficult this would be to implement, as there are extra steps involved than if using google fonts/ CDN.

If the boss is interested in this i can do more work on it..

Regarding this issue, perhaps a mobile optimised version of customizr could be considered?
