### ISSUE TITLE
Bug in Menu Sort Order

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#599]
As reported by a user with online form

> I wanted to report a bug in the latest version of Customizr. The Menu changed to a different location, however we changed it back without a problem. The biggest problem was that we could not control the order of the menu items. They seemed to be random. We reverted to an older version of the theme to fix the problem for now.

**Comment by eri-trabiccolo** [comment]
Well I don't think we changed anything about the menu item orders..
Something like that was reported on the free support forum too (weeks ago, basically when the latest version was released).. we talked about that and we decided that wasn't due to customizr for the reason above :) 
Maybe it's the same user.
My guess was, and still is, that something got lost with the options (maybe a big jump from a very old customizr version.. dunno) and basically a menu location setting was lost. Hence the "new" code fell-back on the pages menu which has an order we don't mess with.
From the user's point of view the two menus (his/her own and a menu of pages) might look exactly the same (same items, if he/she populated it just with pages) but with a different order.. the order criteria set by wp.
User's website might help.
About this:
> We reverted to an older version of the theme to fix the problem for now.

an info about which older version could be useful.

:D
