### ISSUE TITLE
Image inserted in more than one post is not an attachment

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#610]
When an image is inserted in more than one post, it gets attached to only one post.
So, for the other post, it is not considered as an attachement.
If the option **If no featured image is set, use the last image attached to this post** is enable, some posts of this type, do not have any image displayed, though there are images inserted in the post.

See [this post](https://wordpress.org/support/topic/miniature-from-the-first-or-the-only-pictures-in-the-post?replies=5) in support forum.

**Comment by eri-trabiccolo** [comment]
Hello Menaka,
yes we're aware of that, the code charged of that looks through the "image attachments" and not to the images.
And that's how the "attachment thing" works in wordpress.
If you look at the db post table you'll see that attachment are "post" and that each post can have at maximum one "parent". You can attach and detach medias to posts in the media library (easily when viewed as list). There's no bug in it, though I think we have to alter some docs (also some customizer info) to specify this, since I think some of them refer to "images" more than "image attachments" which is more appropriate.
Dunno if changing the code to look through all the images in the content would be a good idea, since as of now the user has some "control" on the image which can be displayed (see the detach thing above).

What do you think?

**Comment by menakas** [comment]
Hi Rocco,
You are right. If it is a known issue and we cannot do anything about it, it has to be communicated. 

IMHO, for a naive user, would things like attaching an image is different from inserting and an image can have only one parent post make sense? It is probably better to keep it very simple for the layman user. Internally, we may choose to do different.

**Comment by eri-trabiccolo** [comment]
Hi Menaka,
well the thing is that is not an issue, but if the user is not informed (misinformed) about that it clearly can be seen as an issue :). My idea is to correctly inform the user where we talk about "first image" with a link to a small doc page which explains what is a wordpress attachment and why sometimes images inside the posts cannot be eligible as attachments (hence as theme's featured image).
From a "code" point of view we can look through the images in the post content whether or not they're attachments, to do that we have to "access" the post content and look for img tags (allow plugin to apply shortcodes before that?). This can be done either "live" each time a post/page featured image needs to be rendered or on post save keeping the result cached somewhere.
I'm not sure about this 'cause, even if it has obvious limits, the attachment thing gives a kind of control to the user who can detach images without removing them from the post content ensuring that the image is still rendered when viewing the single post but not took in account as eligible featured image.
Ball to the boss ;)
