### ISSUE TITLE
Compatibility issue with Simple Vertical Timeline plugin

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#655]
As per [this post](https://wordpress.org/support/topic/simple-vertical-timeline-2/) in the support forum and as verified by me in the local installation, the events of the timeline are not displayed while using this plugin. Seems to be specific to Customizr, because the display is fine with Hueman. The event display uses svg.

**Comment by eri-trabiccolo** [comment]
thanks @menakas for reporting this.

For some reason that plugin hides its blocks when whatever ancestor element has the class `cssanimation`.
In Customizr we use[ Modernizr](https://modernizr.com/) which sets some <html> classes (like the one above) based on the availability of web technologies in the browser in use.
Hueman doesn't use Modernizr.

That's what the plugin does:
- It adds the `is-hidden` class to its relevant elements:
https://plugins.trac.wordpress.org/browser/simple-vertical-timeline/tags/0.0.2/simple-vertical-timeline.php#L164
- In CSS it specifies that the class (combined with `cssanimation`) should hide the element (for a certain viewport):
https://plugins.trac.wordpress.org/browser/simple-vertical-timeline/tags/0.0.2/css/simple-vertical-timeline.css#L94
https://plugins.trac.wordpress.org/browser/simple-vertical-timeline/tags/0.0.2/css/simple-vertical-timeline.css#L229
- It also specifies that replacing `is-hidden` with `bounce-in` the elements should appear with some transition
https://plugins.trac.wordpress.org/browser/simple-vertical-timeline/tags/0.0.2/css/simple-vertical-timeline.css#L96
https://plugins.trac.wordpress.org/browser/simple-vertical-timeline/tags/0.0.2/css/simple-vertical-timeline.css#L231

The latter should be handled in js, but it is not (see the `return` statement):
https://plugins.trac.wordpress.org/browser/simple-vertical-timeline/tags/0.0.2/js/svt-animation.js#L14

Hence the author has a plan for handling the appearing animation  (along with modernizr or something similar)  but it's not in place yet.

The plugin's version is 0.0.2, so not a proper stable version.

Users willing to use it with Customizr, or with anything that uses modernizr, should ask on the plugin support forum, IMHO, since it's a plugin issue.

But they can add the following CSS until the plugin will be ready:
`[class*=svt-].is-hidden { visibility: visible !important; }`

As explained isn't a theme bug so I close this :D

Thanks!

**Comment by menakas** [comment]
Thanks @eri-trabiccolo. Shall pass on the temporary solution. :-)

**Comment by eri-trabiccolo** [comment]
Thanks to your @menakas  ;)
