### ISSUE TITLE
Category filter vs. Sticky post

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#686]
As per this post in the forums, the sticky post is ignored when a category filter is in place.
[https://wordpress.org/support/topic/cant-stick-post-with-category-filters-in-place/](https://wordpress.org/support/topic/cant-stick-post-with-category-filters-in-place/)

I understand it is by design. 

But, users seem to want this: [https://wordpress.org/support/topic/category-filter-kills-expanded-sticky-post/](https://wordpress.org/support/topic/category-filter-kills-expanded-sticky-post/)

Can this be reconsidered? If the sticky post is in one of the filtered categories, why not display it in expanded form?

**Comment by Nikeo** [comment]
@eri-trabiccolo any hint on this ?

**Comment by eri-trabiccolo** [comment]
The reason is that we don't use an actual custom code to treat the sticky posts.
When displaying the blog, and not ignoring the sticky posts, WordPress itself will prepend them to the queried posts (and remove duplicates). But it doesn't filter them according to the param used to specify the categories (or whatever else).
This means that if you're filtering the blog for posts of category X but there's a sticky post of category Y it will still be prepended.
So that's the main reason why we ignore them, and I think this reasonably should not change.
Since we have to ignore them we still suppress our expansion, because we're not sure a sticky post in the first blog page will be displayed as first, we don't even know if it will be there.

So we can consider to improve our code and loop through the sticky posts, find the ones matching our category filter, do our stuff etc etc

**Comment by ghost** [comment]
I'm closing this issue for now.
The current behaviour is not the ideal one but it's a good compromise. Changing this would require too much coding for what is for the moment an edge case => not enough complains about this.

**Comment by eri-trabiccolo** [comment]
@Nikeo 
reported once again:
https://secure.helpscout.net/conversation/1089040225/220251?folderId=607709

do we want to add that notice? :D
