### ISSUE TITLE
Compatibility with photo gallery plugin

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#692]
https://web-dorado.com/products/wordpress-photo-gallery-plugin.html

reported here : https://wordpress.org/support/topic/problem-album-view/

**Comment by eri-trabiccolo** [comment]
Not able to reproduce this issue :|

**Comment by Nikeo** [comment]
ah ok

**Comment by eri-trabiccolo** [comment]
Wrong test.
The problem is the smarload.
That plugin gallery's content is loaded via ajax so the imgs are parsed in php but not smartloaded in js as nothing triggers the loading.
This highlights the real problem of our code: doesn't work with any content retrieved via ajax.
I have a fix to prevent php smartload parsing for ajax request (kinda hacky though), but would be better to improve or js code using event delegation.
