### ISSUE TITLE
{Snippet] Adding sections snippet not working

### ISSUE THREAD

**Issue by menakas** [presscustomizr/customizr#709]
According to[ this post](https://wordpress.org/support/topic/section-for-one-pager-on-homepage-disappeared-after-updating-cutomizr/) on the support forums, this snippet is not working anymore:

[http://presscustomizr.com/snippet/adding-sections-to-any-page-or-posts-in-customizr/](http://presscustomizr.com/snippet/adding-sections-to-any-page-or-posts-in-customizr/)

**Comment by pferdetermine** [comment]
Any news on this? Since the issue is on a live site, this is quite urgent. Thanks for your help!

**Comment by Nikeo** [comment]
Hi @pferdetermine you can ask a developer of our team to work on this as a service.
Please provide the necessary informations [on this page](http://presscustomizr.com/pro-support/), we'll be happy to do it for you.

**Comment by pferdetermine** [comment]
Hi Nicolas, I am just using an existing snippet of YOUR code from your plugin and since the last updates this doesn't work anymore. In your release notes there were no indications that those codes don't work anymore. That's why I am asking you why YOUR code does not work anymore. I expect that your developer team or yourself know what you changed and why your snippet doesn't work anymore. I do not expect any custom coding help. If I had known that this part of the theme didn't work anymore I wouldn't have updated it at all! Thanks for your help!
Best regards,
Kathrin

**Comment by Nikeo** [comment]
Hi Kathrin,
A **snippet is not part of the core theme** and there's no guarantee that it can work after an update. The snippets are chunks of code that we provide for free for our user to help them customize their website. We of course welcome user  who contributes to provide updates for snippets.

Coding takes time and resources. It is a job. Our jobat Press Customizr is to provide the best code for our themes and plugins. We can also provide customizations as a service for users who need it.
Thanks for your understanding.
Best regards,

**Comment by pferdetermine** [comment]
Nicolas, I don't expect any custom coding. I also provide all services for free - and I know what that means. All I expect from you is that you tell me what your changed in your last releases that could lead to the effect that this existing code does not work anymore. In your release notes there were no indications that could lead to this effect. This has got nothing to to with customizations!

**Comment by Nikeo** [comment]
Kathrin, The theme code is too complex to give an answer without analysis.
Doing this analysis would require investigating, understanding, may be testing. This is something taking time and resource.  That's why again, we can debug it for you as a service.
Cheers :)

**Comment by pferdetermine** [comment]
In one release note you mentioned that you renamed "tc" to "czr". In another post I found that tc__f was kept due to compatibility reasons. The only "tc" naming I found in that snippet is
			if ( ! tc__f('__is_home') )
so I guess that this is still correct and not the reason why the code is no longer executed? Or is that something that would have to be changed?

Do you plan to include the functionality for a one pager in customizr in the near future? Since I have some other webpages that are only onepager and that currently are built with customizr, I would have to change the theme if this feature will not be supported in future. (Which would be a shame, because I like your theme very much).
Regards, Kathrin

**Comment by Nikeo** [comment]
Yes, that should not be the reason

One pager : yes this is currently actively developed. Will be available during the first quarter of 2017 for all our Pro themes.
Cheers,

**Comment by pferdetermine** [comment]
Okay, then I will not update the version of my other websites and wait for that new release. 

Any other naming that has been changed or functions that were dismissed in WP or customizr during the last releases (WP 4.7 and since customizr .34 that could be related???

**Comment by pferdetermine** [comment]
Nikeo, one last question since you wrote the snippet - although without any maintenance for sure, but you might remember it: Is there anything that changed in WP 4.7, that could cause the snippet to no longer work? I saw that updating Customizr on my other test-website worked well, but updating to WP 4.7 made the customizr sections disappear! Any hint and idea where to look?
And do you have a release date planned for sections in pro?
