### ISSUE TITLE
double social icons

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#787]
Hi,

User of Customizr theme and Customizr Pro Theme reporting having duplicated social icons.

Issue on WordPress.org forum
https://wordpress.org/support/topic/last-update-double-social-icon-in-footer/

Issue on helpscout
https://secure.helpscout.net/conversation/314014052/22731/?folderId=607544#thread-845085769

I think this is a bug, but I am not able to replicate it on my test site, probably because my test site is a new installation.

Thank you

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
Hi Denzel,
the problem on helpscout is a conflicting plugin which uses a pretty old font-awesome css. In that version they don't scope the icons styling to the 'fa-[icon]' but they apply their style to all the icon-* .
We kept the icon-* for backward compatibility reasons (mainly for old users who used to custom style them).

So since now, basing on our analysis, and on users feedback the reasons for that issue are:
- server side cache (plugin, hosting, cdn) not correctly cleared 
- child-theme messy CSS (e.g. whole copy of old parent CSS in the child-theme)
- plugin conflict

We'll see if we can avoid this, but the downside will be for the old customers who are not affected by the problems above and wanted to style the social icons.

**Comment by denzelchia** [comment]
Hi Rocco,

Thank you very much for these information! 👍 
Glad to know it's not a theme bug.

I will use your information as reference in support forum.

Have a nice day, :)

Best Regards,
Denzel
