### ISSUE TITLE
Disable zoom in mobiles?

### ISSUE THREAD

**Issue by eri-trabiccolo** [presscustomizr/customizr#802]
https://wordpress.org/support/topic/suggestion-disable-zoom-on-mobile/

Not sure, I can understand the layout might break (I think it depends on the browser) but if someone wants to zoom a text, that should be allowes

**Comment by PeopleInside** [comment]
Hi,
I tested this in Firefox MOBILE but maybe is the same in Chrome MOBILE.

As this is an HTML 5 I think is not needed to zoom because content are adapted to the screen. In the phone you have the touch maybe today also in some PC and if you zoom with fingers is not something beautiful to see. ... Si I tried other HTML 5 themes and I saw that zoom are not allowed and theme was showed correctly.

In any case I have fixed this with the code
`<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />` in the header.

**Comment by eri-trabiccolo** [comment]
Hi PeopleInside,
I see your point.

The content are indeed adapted to the screen, but still a user might want to zoom the text, that was the point.
Anyway that code might not work on all the browsers (specifically safari's ios).

Thanks for your contribution! :)

Rocco

**Comment by PeopleInside** [comment]
Thanks. Tested in Safari IOS and seems working.

**Comment by eri-trabiccolo** [comment]
Perfect, thanks for this feedback! :D
