### ISSUE TITLE
Unable to remove featured image per post

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#815]
Hi,

This issue happens on both Customizr and Customizr Pro Theme.
Reported by user on helpscout.
https://secure.helpscout.net/conversation/323378614/23785/?folderId=607546

I am able to replicate the issue.

In Appearance -> Customize -> Content -> Single posts
Find the setting -> Post thumbnail position
Select any position to display.

Go to single.php view of any post that has a featured image.
Edit the post to remove the featured image. 
Update the post.
View post on front end, the post is still showing the featured image, instead of no featured image.

Please see my screen-cast of the above mentioned steps.
http://screencast-o-matic.com/watch/cbn0V06Fi6

Best Regards,
Denzel

**Comment by eri-trabiccolo** [comment]
I think it depends on the fact that the image is attached to the post (can you check the media is attached to it?), and the theme displays the first attachment there if a certain option (which btw is for the lists of posts)  is checked.

This is a bug since ages:
https://github.com/presscustomizr/customizr/blob/v3.3.19/inc/parts/class-content-post_thumbnails.php#L175

(see the double == instead of the assignment ).

So we can fix the bug but users used to see the first attachment there might feel that as regression.

Do we want to fix this anyways @nikeo ? 
I think so, do we want to add a new option controlling this in singles?

**Comment by Nikeo** [comment]
@denzelchia thanks for reporting this problem.
@eri-trabiccolo yes let's fix it, I'll publish a note about the potential regression for users who were used to this bug.
Thanks

**Comment by Nikeo** [comment]
@eri-trabiccolo you fixed it already so cool
No additional options needed.
