### ISSUE TITLE
Buddypress : some display problems reported

### ISSUE THREAD

**Issue by Nikeo** [presscustomizr/customizr#825]
Profile page issue https://www.projetentreprise.fr/communaute/faridhadda/profile/

font too small  https://www.projetentreprise.fr/wikicrea/forum/projet-entreprise/

**Comment by eri-trabiccolo** [comment]
- profile page:
conflicts with b2.3.2 labels and buddypress td
this should revert the issue
`td.label {
    color: inherit;
    display: table-cell;
    white-space: normal;
}`

- font too small:
reported also for hueman. But the problem is that bbpress itself sets the font to 12px.
<img width="746" alt="bbpress" src="https://cloud.githubusercontent.com/assets/7689242/23379320/d2f8c782-fd36-11e6-8b77-c45d13ea971a.PNG">
Anyway we can add our CSS code. But that's, to me, remains a bbpress issue.

p.s.
the forum is powered by bbpress, so different plugin. maybe we should open a different issue.
