### ISSUE TITLE
No additional css option for administrator in WordPress multisite installation

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#860]
Hi,

In WordPress multi-site, only global administrator can see the additional css option.

Please see this thread for the details.
https://wordpress.org/support/topic/multisite-site-admins-cant-edit-their-custom-css-anymore/

Thank you

**Comment by eri-trabiccolo** [comment]
Yeah,
'cause we switched our old option to the WordPress core one, due to theme review guidelines.
The WordPress core one doesn't show for site admins only.
There's a plugin that sould allow that:
https://fuc.wordpress.org/plugins/multisite-custom-css/

Is this something we have to consider? If yes, how (since we still have to respect those guidelines)?

Use case:

- users of Customizr before 3.5.5 might have set up a Custom CSS for a site in their multisite's network as site Administrator using our old Custom CSS control.

- updating the theme to Customizr 3.5.5+ the old custom CSS will be "moved" into the core option, but the core control will be not visible for simple site's administrators

- The CSS then will still be applied with no way for site's admins to change it.

We should probably just suggest to use the plugin above as we're not "allowed" to have our old custom control.

**Comment by denzelchia** [comment]
Hi Rocco,

> We should probably just suggest to use the plugin above as we're not "allowed" to have our old custom control.

Thank you very much for your reply.
I agree with your suggestion. :) 👍
